### ISSUE TITLE
Build issue in source connector

### ISSUE THREAD

**Issue by dhgoelmsft** [Azure/toketi-kafka-connect-iothub#22]
connector.class=com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector

needs to be replaced with

connector.class=com.microsoft.azure.iot.kafka.connect.IotHubSourceConnector

in the https://github.com/Azure/toketi-kafka-connect-iothub/blob/master/connect-iothub-source.properties file

**Comment by varunpuranik** [comment]
@dhgoelmsft - Thanks for reporting the issue. Are you running into this when using the pre-built jars in one of the releases? If so, then I need to do a new release with the latest bits, as the bits have now changed (I haven't done that yet because of signing issues). 
The only supported way now is to build the bits from source as described in the Readme. With the jar built from the sources, the connector.class==com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector will work as expected.
