### ISSUE TITLE
Connector in Distributed mode

### ISSUE THREAD

**Issue by khajaasmath786** [Azure/toketi-kafka-connect-iothub#8]
We have cloudera cluster with 3 kafka brokers in it. In this case, do we need to run standalone script from all the 3 brokers or only the edge node?

can you also provide steps to run it in distributed mode too? also we are in cluster with JDK 1.7, is there any requirement for this connector to be on JDK 1.8?

**Comment by khajaasmath786** [comment]
any suggestions or documentation for my questions?

**Comment by syedhassaanahmed** [comment]
+1

**Comment by varunpuranik** [comment]
The way to run Kafka Connect IoTHub in Distributed mode is same as any other Kafka Connector in distributed mode. The only 2 interesting changes would be - 
1. The Kafka Connect IoTHub jar should be binplaced in the libs folder of the Kafka installation on all the nodes, so that the Kafka Connect can find it the source/sink connector
2. The configuration should include the Kafka Connect IoTHub properties (with values same as Sandalone mode)
For information on how to start Kafka Connect in Distributed mode, please refer to the Kafka documentation - https://docs.confluent.io/3.0.0/connect/userguide.html#rest-interface

**Comment by syedhassaanahmed** [comment]
@varunpuranik Can you please also fix the Kafka Connect IoTHub jar file in releases as described in this issue? https://github.com/Azure/toketi-kafka-connect-iothub/issues/10
Thanks

**Comment by varunpuranik** [comment]
As I mentioned previously, Kafka documentation is the best place to get more information to run connectors in Distributed mode (and the various knobs to use in that mode). This connector code has been tested to work in distributed mode. I will close this issue.
